RentiSI/Areas/Admin/Controllers/RevisionController.cs
using Microsoft.AspNetCore.Mvc;
using RentiSI.AccesoDatos.Data.Repository.IRepository;
using RentiSI.Modelos;
using System.Security.Claims;

namespace RentiSI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RevisionController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        public RevisionController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var usuarioActual = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var revisiones = _contenedorTrabajo.Revision.ObtenerRevisiones();

            return View(revisiones);

        }

        [HttpGet]
        public IActionResult ConsultarPorPlaca(string Placa)
        {
            return View(_contenedorTrabajo.Tramite.GetAll(r => r.NumeroPlaca == Placa));

        }


    }
}

RentiSI/Areas/Admin/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using RentiSI.AccesoDatos.Data.Repository.IRepository;
using RentiSI.AccesoDatos.Migrations;
using RentiSI.Modelos;
using RentiSI.Modelos.viewModels;
using System.Collections.Generic;
using System.Data;
using System.Runtime.CompilerServices;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;

namespace RentiSI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrador")]
    [Area("Admin")]
    public class UsuariosController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        private readonly UserManager<ApplicationUser> _userManager;

        public UsuariosController(IContenedorTrabajo contenedorTrabajo, UserManager<ApplicationUser> userManager)
        {
            _contenedorTrabajo = contenedorTrabajo;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Usuario.GetAll() });
        }
        [HttpGet]
        public IActionResult Bloquear(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            _contenedorTrabajo.Usuario.BloquearUsuario(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Desbloquear(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            _contenedorTrabajo.Usuario.DesbloquearUsuario(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            UsuarioVM usuarioVM = new UsuarioVM()
            {
                Usuario = user
            };

            return View(usuarioVM);
        }
        [HttpGet]
        public async Task<IActionResult> EditRol(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var roles = await _userManager.GetRolesAsync(user);
            if (roles == null)
            {
                return NotFound();
            };

            RolVM rolVM = new RolVM()
            {
                Usuario = user,
                Rol = roles.FirstOrDefault()
            };

            return View(rolVM);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(UsuarioVM usuarioVM)
        {
            if (ModelState.IsValid)
            {
               
                var usuario =  await _userManager.FindByIdAsync(usuarioVM.Usuario.Id);
                if (usuario != null)
                {
                    var newPasswordHash = _contenedorTrabajo.Usuario.HashPassword(usuarioVM.Password);
                    usuario.PasswordHash = newPasswordHash;
                    var resultado= await _userManager.UpdateAsync(usuario);

                    if (resultado.Succeeded)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
            }

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> EditRol(RolVM rolVM)
        {
            if (ModelState.IsValid)
            {
                var usuario = await _userManager.FindByIdAsync(rolVM.Usuario.Id);
                if (usuario != null)
                {
                    var rol = ObtenerRoles(rolVM.Usuario.Id).Result;

                    var respuestaEliminarRol = await RemoveRoleFromUserAsync(usuario, rol.FirstOrDefault());
                    if (respuestaEliminarRol)
                    {
                        await AgregarRol(usuario, rolVM.Rol);
                    }

                    usuario.Nombre = rolVM.Usuario.Nombre;
                    usuario.Email = rolVM.Usuario.Email;
                    var resultado = await _userManager.UpdateAsync(usuario);
                    if (resultado.Succeeded)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
            }

            return View();
        }  
        private async Task<IList<string>> ObtenerRoles(string usuarioId)
        {
            var usuario = await _userManager.FindByIdAsync(usuarioId);
            return await _userManager.GetRolesAsync(usuario);
        }
        private async Task<bool> RemoveRoleFromUserAsync(ApplicationUser usuarioId, string rol)
        {
            var result = await _userManager.RemoveFromRoleAsync(usuarioId, rol);
            return result.Succeeded;

         }
         private async Task<bool> AgregarRol(ApplicationUser usuario, string rol)
         {
             var resultado = await _userManager.AddToRoleAsync(usuario, rol);
             return resultado.Succeeded;
        }
    }
}

RentiSI/Areas/Cliente/Controllers/AsignacionesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using RentiSI.AccesoDatos.Data.Repository.IRepository;
using RentiSI.Areas.Operativo.Controllers;
using RentiSI.Modelos;
using RentiSI.Modelos.viewModels;
using RentiSI.Utilidades;
using System.Globalization;
using System.Security.Policy;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace RentiSI.Areas.Cliente.Controllers
{
    [Authorize(Roles = "Cliente, Administrador")]
    [Area("Cliente")]
    public class AsignacionesController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        private readonly UserManager<ApplicationUser> _userManager;
        private ErrorLog errorLog= new ErrorLog();
        public AsignacionesController(IContenedorTrabajo contenedorTrabajo, UserManager<ApplicationUser> userManager)
        {
            _contenedorTrabajo = contenedorTrabajo;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            try
            {
                TramiteVM tramiteVM = new TramiteVM()
                {
                    Tramite = new Tramite(),
                    ListaOrganismosTransito = _contenedorTrabajo.OrganismoTransito.GetListaOrganismosTransito(),
                    ListaTipoGestion = _contenedorTrabajo.TipoCasuistica.GetListaTipoCasuisticaPorModulo("TIPO_GESTION")
            };
                return View(tramiteVM);
            }
            catch (Exception ex)
            {
                
                return View();
            } 
        }
        [HttpPost]
        public IActionResult Create(TramiteVM tramiteVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    tramiteVM.Tramite.FechaCreacion = DateTime.Now;
                    tramiteVM.Tramite.IdUsuarioAsignacion = _userManager.GetUserId(User);
                    string placaValida = _contenedorTrabajo.Asignacion.validarPlacas(tramiteVM.Tramite.NumeroPlaca);
                    if (string.IsNullOrEmpty(placaValida))
                    {
                        if (_contenedorTrabajo.Asignacion.ExistePlaca(tramiteVM.Tramite.NumeroPlaca))
                        {
                            TempData["Mensaje"] = "La placa ya se encuentra registrada, aun asi se creó en el sistema.";
                        }
                            _contenedorTrabajo.Asignacion.Add(tramiteVM.Tramite);
                            _contenedorTrabajo.Save();

                            InsertarTipoGestion(tramiteVM);

                            return RedirectToAction(nameof(Index));   
                    }
                    else
                    {
                     
                        ModelState.AddModelError("Tramite.NumeroPlaca", placaValida);
                    }
                }
            }
            catch (Exception ex)
            {
               
            }

            tramiteVM.ListaOrganismosTransito = _contenedorTrabajo.OrganismoTransito.GetListaOrganismosTransito();
            tramiteVM.ListaTipoGestion = _contenedorTrabajo.TipoCasuistica.GetListaTipoCasuisticaPorModulo("TIPO_GESTION");
            return View(tramiteVM);
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Asignacion.GetAll(includeProperties: "OrganismosDeTransito") });
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            try
            {
                TramiteVM tramiteVM = new TramiteVM()
                {
                    Tramite = new Tramite(),
                    ListaOrganismosTransito = _contenedorTrabajo.OrganismoTransito.GetListaOrganismosTransito(),
                    ListaTipoGestion = _contenedorTrabajo.TipoCasuistica.GetListaTipoCasuisticaPorModulo("TIPO_GESTION"),
                    SelectedTipoGestionIds = _contenedorTrabajo.TipoGestion.GetAll(tipoGestion => tipoGestion.TramiteId == id)
                                                     .Select(tipoGestion => tipoGestion.TipoGestionId)
                                                     .ToArray()
            };

                if (id != null)
                {
                    tramiteVM.Tramite = _contenedorTrabajo.Tramite.Get(id.GetValueOrDefault());
                }

                return View(tramiteVM);
            }
            catch (Exception ex)
            {
               
                return View();
            }

        }

        [HttpPost]
        public IActionResult Edit(TramiteVM tramiteVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    tramiteVM.Tramite.IdUsuarioAsignacion = _userManager.GetUserId(User);

                    //Logica para actualizar en BD
                    _contenedorTrabajo.Asignacion.Actualizar(tramiteVM.Tramite);
                    _contenedorTrabajo.Save();

                    InsertarTipoGestion(tramiteVM);

                    return RedirectToAction(nameof(Index));
                }

            }
            catch (Exception ex)
            {
               
            }

            tramiteVM.ListaOrganismosTransito = _contenedorTrabajo.OrganismoTransito.GetListaOrganismosTransito();
            tramiteVM.ListaTipoGestion = _contenedorTrabajo.TipoCasuistica.GetListaTipoCasuisticaPorModulo("TIPO_GESTION");
            return View(tramiteVM);
        }

        private void InsertarTipoGestion(TramiteVM tramiteVM)
        {
            try
            {
                if (tramiteVM.Tramite.Id != 0)
                {
                    var tipoRevision = _contenedorTrabajo.TipoGestion.
                                               GetAll(tipoGestion => tipoGestion.TramiteId == tramiteVM.Tramite.Id).ToArray();

                    if (tipoRevision.Any())
                    {
                        //Se remueven antes de actualizarlos
                        _contenedorTrabajo.TipoGestion.RemoveRange(tipoRevision);
                        _contenedorTrabajo.Save();
                    }
                }

                if (tramiteVM.SelectedTipoGestionIds != null)
                {
                    foreach (var tipoGestionId in tramiteVM.SelectedTipoGestionIds)
                    {
                        _contenedorTrabajo.TipoGestion.Add(new TipoGestion()
                        {
                            TramiteId = tramiteVM.Tramite.Id,
                            TipoGestionId = tipoGestionId
                        });
                        _contenedorTrabajo.Save();
                    }
                }
            }
            catch (Exception ex)
            {
                errorLog.RegistrarError(ex.Message, nameof(AsignacionesController));
            }
        }
    }
}

RentiSI/Areas/Coordinador/Controllers/RecepcionController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RentiSI.AccesoDatos.Data.Repository.IRepository;
using RentiSI.Areas.Cliente.Controllers;
using RentiSI.Modelos;
using RentiSI.Modelos.viewModels;
using RentiSI.Utilidades;

namespace RentiSI.Areas.Coordinador.Controllers
{
    [Area("Coordinador")]
    public class RecepcionController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        private readonly UserManager<ApplicationUser> _userManager;

        private ErrorLog errorLog = new ErrorLog();

        public RecepcionController(IContenedorTrabajo contenedorTrabajo, UserManager<ApplicationUser> userManager)
        {
            _contenedorTrabajo = contenedorTrabajo;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Recepcion.ObtenerRecepciones() });

        }

        [HttpGet("/Coordinador/Recepcion/Edit/{recepcionId}")]
        public IActionResult Edit(int recepcionId)
        {
            var recepciones = _contenedorTrabajo.Recepcion.ObtenerRecepcionesPorId(recepcionId);
            if (recepciones != null)
            {
                recepciones.ListaOrganismosTransito = _contenedorTrabajo.OrganismoTransito.GetListaOrganismosTransito();
            }
            return View(recepciones);
        }

        [HttpPost]
        public IActionResult Update(ResponseViewModel responseViewModel)
        {
            try
            {

                var recepcion = _contenedorTrabajo.Recepcion.GetAll(recepcion => recepcion.RecepcionId == responseViewModel.Recepcion.RecepcionId).FirstOrDefault();
                if (recepcion != null)
                {
                    recepcion.Observacion = responseViewModel.Recepcion.Observacion;
                    recepcion.FechaRecepcion = DateTime.Now;
                    recepcion.IdUsuarioRecepcion = _userManager.GetUserId(User);
                    recepcion.EsRecepcion = responseViewModel.Recepcion.EsRecepcion;

                    _contenedorTrabajo.Recepcion.Actualizar(recepcion);
                }
            }
            catch (Exception ex)
            {

                errorLog.RegistrarError(ex.Message, nameof(RecepcionController));
            }

            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        public IActionResult Create(ResponseViewModel responseViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    responseViewModel.Recepcion.FechaRecepcion = DateTime.Now;
                    responseViewModel.Recepcion.IdUsuarioRecepcion = _userManager.GetUserId(User);
                    responseViewModel.Recepcion.Id_Tramite = responseViewModel.Tramite.Id;
                    _contenedorTrabajo.Recepcion.Add(responseViewModel.Recepcion);
                    _contenedorTrabajo.Save();
                }

            }
            catch (Exception ex)
            {
                errorLog.RegistrarError(ex.Message, nameof(RecepcionController));
            }

            return RedirectToAction(nameof(Index));

        }

        [HttpGet("/Coordinador/Recepcion/Create/{tramiteId}")]
        public IActionResult Create(int tramiteId)
        {
            var tramite = _contenedorTrabajo.Tramite.Get(tramiteId);
            ResponseViewModel responseViewModel = new ResponseViewModel()
            {
                ListaOrganismosTransito = _contenedorTrabajo.OrganismoTransito.GetListaOrganismosTransito(),
                Tramite = tramite,
                FechaAsignacion = tramite.FechaCreacion.Value.ToString("dd-MM-yyyy")
            };

            return View(responseViewModel);
        }
    }
}

RentiSI/Views/Shared/PageNotFound.cshtml
@{
    ViewData["Title"] = "Error 404 - Página no encontrada";
}

<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="text-center">
                <h1 class="display-4">¡Oops!</h1>
                <p class="lead">La página que buscas no se encontró.</p>
                <p>Es posible que la página haya sido eliminada, que su nombre haya cambiado o que esté temporalmente fuera de servicio.</p>
                <a href="/" class="btn btn-primary">Ir a la página de inicio</a>
            </div>
        </div>
    </div>
</div>

RentiSI/Views/Shared/_Layout.cshtml
@using RentiSI.Utilidades
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RentiSI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/Bootstrap5.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/RentiSI.styles.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.10.5/sweetalert2.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RentiSI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(CNT.Administrador))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                            </li>   
                        }
                        @if (User.IsInRole(CNT.Cliente) || User.IsInRole(CNT.Administrador))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Cliente" asp-controller="Asignaciones" asp-action="Index">Asignación</a>
                            </li>
                        }
                        @if (User.IsInRole(CNT.Coordinador) || User.IsInRole(CNT.Administrador))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Coordinador" asp-controller="Recepcion" asp-action="Index">Recepción</a>
                            </li>
                        }
                        @if (User.IsInRole(CNT.OperativoImpronta) || User.IsInRole(CNT.Administrador))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="OperativoImpronta" asp-controller="GestionImpronta" asp-action="Index">Gestión Improntas</a>
                            </li>
                        }
                        @if (User.IsInRole(CNT.Operativo) || User.IsInRole(CNT.Administrador))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Operativo" asp-controller="Revision" asp-action="Index">Revisión</a>
                            </li>
                        }
                        @if (User.IsInRole(CNT.Coordinador) || User.IsInRole(CNT.Administrador))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Coordinador" asp-controller="GestionTramite" asp-action="Index">Gestión Trámites</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Coordinador" asp-controller="Reasignacion" asp-action="Index">Reasignación</a>
                            </li>
                        }
                    </ul>


                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @DateTime.Now.Year - RentiSI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.0/js/dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/3.2.1/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.10.5/sweetalert2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RentiSI/Views/Shared/_VistaCrearVolver.cshtml
@model object

@{
    var boton = Model.GetType().GetProperty("LabelBoton").GetValue(Model);
    var claseBoton = Model.GetType().GetProperty("ClaseBoton").GetValue(Model);
}

<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-@claseBoton form-control" onclick="this.disabled=true; this.value='Procesando...'; this.form.submit();">@boton</button>
    </div>

    <div class="col">
        <a asp-action="Index" class="btn btn-secondary form-control">Volver atrás</a>
    </div>
</div>